sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.0

# CodeClimate Test Reporter
env:
  global:
    - CC_TEST_REPORTER_ID=85ec0a91376be74d800a1e40b70953d95e83c102d67489c6db7d31c5d3858e88
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
